In [72]:
import numpy as np

In [73]:
betas = np.array([[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0]])


x_5_rows = np.array([[1.0,1.0,1.0,1.0],
            [1.0,2.0,3.0,4.0],
             [1.0,1.0,1.0,1.0],
             [1.0,2.0,3.0,4.0],
             [1.0,1.0,1.0,1.0]])

alpha_5_rows = np.array([[2.0,3.0],
                  [5.0,5.0],
                  [2.0,3.0],
                  [5.0,5.0],
                  [2.0,3.0]])

In [74]:
def compute_gradient_matrix_cookbook_5_rows(x_row,alpha_row,beta):
    return 2*(np.dot(beta,np.outer(x_row,x_row.T)).T - (np.outer(x_row,alpha_row)))

In [75]:
step_size = .001

In [76]:
for val in range(100):
    gradient_matrix_global = np.zeros(beta.shape)
    loss_overall = np.zeros(alpha_hat.shape)

    for row_idx in range(len(x_5_rows)):
        alpha_actual = np.expand_dims(alpha_5_rows[row_idx],-1)
        x_row = np.expand_dims(x_5_rows[row_idx],-1)
        alpha_hat = betas.dot(x_row)
        difference = alpha_actual-alpha_hat
        loss_overall+=difference

        gradient_matrix_local = compute_gradient_matrix_cookbook_5_rows(x_row,alpha_actual,betas).T
        gradient_matrix_global+= gradient_matrix_local
    betas += -step_size*gradient_matrix_global
    print(loss_overall)

[[-16.]
 [-13.]]
[[-13.816]
 [-11.008]]
[[-11.938816]
 [ -9.296608]]
[[-10.32531482]
 [ -7.82637261]]
[[-8.93842717]
 [-6.56338874]]
[[-7.7462952 ]
 [-5.47851789]]
[[-6.72153978]
 [-4.54671802]]
[[-5.84063092]
 [-3.74646764]]
[[-5.0833466 ]
 [-3.05927089]]
[[-4.43230772]
 [-2.46923216]]
[[-3.87257843]
 [-1.96269057]]
[[-3.39132265]
 [-1.52790573]]
[[-2.97750887]
 [-1.15478782]]
[[-2.62165643]
 [-0.83466549]]
[[-2.31561754]
 [-0.56008648]]
[[-2.05238986]
 [-0.3246462 ]]
[[-1.82595547]
 [-0.12284049]]
[[-1.63114248]
 [ 0.05006103]]
[[-1.4635061]
 [ 0.1981237]]
[[-1.31922641]
 [ 0.32484131]]
[[-1.19502052]
 [ 0.43321649]]
[[-1.08806705]
 [ 0.52582972]]
[[-0.99594126]
 [ 0.6048987 ]]
[[-0.91655932]
 [ 0.67232935]]
[[-0.84813032]
 [ 0.72975963]]
[[-0.78911515]
 [ 0.77859723]]
[[-0.73819107]
 [ 0.82005194]]
[[-0.69422127]
 [ 0.85516344]]
[[-0.6562288 ]
 [ 0.88482526]]
[[-0.62337401]
 [ 0.9098053 ]]
[[-0.59493533]
 [ 0.9307635 ]]
[[-0.57029259]
 [ 0.94826701]]
[[-0.54891285]
 [ 0.96280325]]
[

In [77]:
betas.dot(x_row)

array([[2.17177792],
       [2.56804148]])

In [55]:
row_idx

4

In [78]:
for row_idx in range(len(x_5_rows)):
    x_row = np.expand_dims(x_5_rows[row_idx],-1)
    alpha_hat = betas.dot(x_row)
    print(alpha_hat)

[[2.17177792]
 [2.56804148]]
[[4.91159732]
 [5.2223058 ]]
[[2.17177792]
 [2.56804148]]
[[4.91159732]
 [5.2223058 ]]
[[2.17177792]
 [2.56804148]]
