In [122]:
import numpy as np

In [123]:
beta = np.array([[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0]])
x = np.array([1.0,1.0,1.0,1.0])
alpha = np.array([1.0,1.0])

In [124]:
def compute_gradient_matrix_cookbook(x,alpha,beta):
    return 2*(np.dot(beta,np.outer(x,x.T)).T - (np.outer(x,alpha)))

In [125]:
def compute_difference(beta,x):
    alpha_hat = (beta).dot(x)
    difference = alpha_hat-alpha
    
    return difference

In [126]:
def sse(difference):
    return (difference.T).dot(difference) 

In [127]:
def compute_gradient_manual(beta,x,index_values,delta=0.00001):
    row,col = index_values
    difference1 = compute_difference(beta,x)
    
    beta_copy = beta.copy()
    beta_copy[row,col]+=0.00001
    
    difference2 = compute_difference(beta_copy,x)
        
    return (sse(difference1)-sse(difference2))/delta

In [128]:
alpha_hat = (beta).dot(x)
difference = alpha_hat-alpha

In [129]:
#cookbook gradient
compute_gradient_matrix_cookbook(x,alpha,beta)

array([[6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.]])

In [130]:
x.shape

(4,)

In [131]:
#manual gradient verification

gradient_matrix_manual = np.zeros(beta.shape)

for val in range(len(beta)):
    for valtwo in range(len(beta[0])):
        partial_gradient = compute_gradient_manual(beta,x,(val,valtwo))
        gradient_matrix_manual[val,valtwo]=partial_gradient
        
gradient_matrix_manual.T

array([[-6.00001, -6.00001],
       [-6.00001, -6.00001],
       [-6.00001, -6.00001],
       [-6.00001, -6.00001]])

In [132]:
gradient_matrix_manual.T

array([[-6.00001, -6.00001],
       [-6.00001, -6.00001],
       [-6.00001, -6.00001],
       [-6.00001, -6.00001]])

# Gradient 5 Rows

In [133]:
beta = np.array([[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0]])
x_5_rows = np.array([[1.0,1.0,1.0,1.0],
            [1.0,1.0,1.0,1.0],
             [1.0,1.0,1.0,1.0],
             [1.0,1.0,1.0,1.0],
             [1.0,1.0,1.0,1.0]])
alpha_5_rows = np.array([[1.0,1.0],
                  [1.0,1.0],
                  [1.0,1.0],
                  [1.0,1.0],
                  [1.0,1.0]])

In [134]:
def compute_difference(beta,x_row,alpha_row):
    alpha_hat = (beta).dot(x_row)
    difference = alpha_hat-alpha_row
    
    return difference

In [135]:
def compute_gradient_manual(beta,x_row,alpha_row,index_values,delta=0.00001):
    row,col = index_values
    difference1 = compute_difference(beta,x_row,alpha_row)
    
    beta_copy = beta.copy()
    beta_copy[row,col]+=0.00001
    
    difference2 = compute_difference(beta_copy,x_row,alpha_row)
        
    return (sse(difference1)-sse(difference2))/delta

In [136]:
gradient_matrix_global = np.zeros(beta.shape)

for row_index in range(len(x_5_rows)):
    row = x_5_rows[row_index]
    alpha_row = alpha_5_rows[row_index]
    gradient_matrix_local = np.zeros(beta.shape)

    for val in range(len(beta)):
        for valtwo in range(len(beta[0])):
            partial_gradient = compute_gradient_manual(beta,x,alpha_row,(val,valtwo))
            gradient_matrix_local[val,valtwo]=partial_gradient
    gradient_matrix_global+= gradient_matrix_local


In [137]:
gradient_matrix_global

array([[-30.00005, -30.00005, -30.00005, -30.00005],
       [-30.00005, -30.00005, -30.00005, -30.00005]])

In [138]:
def compute_gradient_matrix_cookbook_5_rows(x_row,alpha_row,beta):
    return 2*(np.dot(beta,np.outer(x_row,x_row.T)).T - (np.outer(x_row,alpha_row)))

In [139]:
gradient_matrix_global = np.zeros(beta.shape)

for row_index in range(len(x_5_rows)):
    row = x_5_rows[row_index]
    alpha_row = alpha_5_rows[row_index]
    gradient_local = compute_gradient_matrix_cookbook_5_rows(row,alpha_row,beta).T
    gradient_matrix_global+=gradient_local

In [140]:
gradient_matrix_global

array([[30., 30., 30., 30.],
       [30., 30., 30., 30.]])

# Gradient Descent

In [121]:
betas_random = np.random.random((beta.shape))