In [1]:
import numpy as np

In [2]:
betas = np.array([[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0]])


x_5_rows = np.array([[1.0,1.0,1.0,1.0],
            [1.0,2.0,3.0,4.0],
             [1.0,1.0,1.0,1.0],
             [1.0,2.0,3.0,4.0],
             [1.0,1.0,1.0,1.0]])

alpha_5_rows = np.array([[2.0,3.0],
                  [5.0,5.0],
                  [2.0,3.0],
                  [5.0,5.0],
                  [2.0,3.0]])

In [3]:
for val in range(10):
    print(val)

0
1
2
3
4
5
6
7
8
9


In [4]:
def compute_gradient_matrix_cookbook_5_rows(x_row,alpha_row,beta):
    return 2*(np.dot(beta,np.outer(x_row,x_row.T)).T - (np.outer(x_row,alpha_row)))

In [5]:
step_size = .001

In [8]:
for val in range(100):
    gradient_matrix_global = np.zeros(betas.shape)
    loss_overall = np.zeros((2,1))

    for row_idx in range(len(x_5_rows)):
        alpha_actual = np.expand_dims(alpha_5_rows[row_idx],-1)
        x_row = np.expand_dims(x_5_rows[row_idx],-1)
        alpha_hat = betas.dot(x_row)
        difference = alpha_actual-alpha_hat
        loss_overall+=difference

        gradient_matrix_local = compute_gradient_matrix_cookbook_5_rows(x_row,alpha_actual,betas).T
        gradient_matrix_global+= gradient_matrix_local
    betas += -step_size*gradient_matrix_global
    if val%10==0:
        print('epoch :',val,' loss:',loss_overall)

epoch : 0  loss: [[-16.]
 [-13.]]
epoch : 10  loss: [[-3.87257843]
 [-1.96269057]]
epoch : 20  loss: [[-1.19502052]
 [ 0.43321649]]
epoch : 30  loss: [[-0.59493533]
 [ 0.9307635 ]]
epoch : 40  loss: [[-0.45186525]
 [ 1.01203033]]
epoch : 50  loss: [[-0.40962226]
 [ 1.0027438 ]]
epoch : 60  loss: [[-0.38990398]
 [ 0.97446655]]
epoch : 70  loss: [[-0.3754874]
 [ 0.9428973]]
epoch : 80  loss: [[-0.36257513]
 [ 0.91145695]]
epoch : 90  loss: [[-0.35032112]
 [ 0.88086874]]


In [9]:
betas.dot(x_row)

array([[2.17177792],
       [2.56804148]])

In [55]:
row_idx

4

In [78]:
for row_idx in range(len(x_5_rows)):
    x_row = np.expand_dims(x_5_rows[row_idx],-1)
    alpha_hat = betas.dot(x_row)
    print(alpha_hat)

[[2.17177792]
 [2.56804148]]
[[4.91159732]
 [5.2223058 ]]
[[2.17177792]
 [2.56804148]]
[[4.91159732]
 [5.2223058 ]]
[[2.17177792]
 [2.56804148]]
